"""add labour tables

Revision ID: 135cac4ad087
Revises: 2d010f388f12
Create Date: 2026-02-28 23:25:43.460088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135cac4ad087'
down_revision: Union[str, None] = '2d010f388f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labour_work',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('labour_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('press_count', sa.Integer(), nullable=False),
    sa.Column('rate_per_piece', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['labour_id'], ['labours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour_work')
    op.drop_table('labours')
    # ### end Alembic commands ###
