"""item_status

Revision ID: f764a17d46f7
Revises: 135cac4ad087
Create Date: 2026-03-05 19:57:52.840698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f764a17d46f7'
down_revision: Union[str, None] = '135cac4ad087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('entry_items', sa.Column('item_status', sa.String(length=20), nullable=False, server_default='pending'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_items', sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('entry_items', 'item_status')
    # ### end Alembic commands ###
